/**************************************************************************************************\
 *** 
 *** Simulink model       : RadarTestbench_drivesctl_MATLAB20b
 *** TargetLink subsystem : RadarTestbench_drivesctl_MATLAB20b/rtblogic
 *** Codefile             : rtblogic.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2021-11-12 16:03:26
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : disabled
 *** Logging mode                             : According to block-specific data
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\dSPACE_Rel2020b\dSPACE TargetLink 5.1\Matlab\Tl\C
 ***                                            onfig\codegen\cconfig.xml
 *** Root style sheet                         : C:\dSPACE_Rel2020b\dSPACE TargetLink 5.1\Matlab\Tl\X
 ***                                            ML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.1p1 from 30-Jul-2021
 *** Code generator version  : Build Id 5.1.0.30 from 2021-07-30 12:58:34
\**************************************************************************************************/

#ifndef RTBLOGIC_H
#define RTBLOGIC_H

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_basetypes.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GLOBAL: global variables (RAM) | Width: 64
\**************************************************************************************************/
extern Float64 Sa1_angle_az_deg_;
extern Float64 Sa1_angle_el_deg_;
extern Float64 Sa5_CorrectionFactor_M1;
extern Float64 Sa5_CorrectionFactor_M2;

/**************************************************************************************************\
   GLOBAL: global variables (RAM) | Width: 32
\**************************************************************************************************/
extern UInt32 Sa1_Motor_1_Mo___submode_select;
extern Int32 Sa1_Motor_1_Po__on_actual_value;
extern Int32 Sa1_Motor_1_Target_Position;
extern Int32 Sa1_Motor_1_VelocityActualValue;
extern UInt32 Sa1_Motor_2_Mo___submode_select;
extern Int32 Sa1_Motor_2_Po__on_actual_value;
extern Int32 Sa1_Motor_2_Target_Position;
extern Int32 Sa1_Motor_2_VelocityActualValue;
extern UInt32 Sa1_OperationModes___;

/**************************************************************************************************\
   GLOBAL: global variables (RAM) | Width: 16
\**************************************************************************************************/
extern UInt16 Sa1_Motor_1_Controlword;
extern UInt16 Sa1_Motor_1_Statusword;
extern UInt16 Sa1_Motor_2_Controlword;
extern UInt16 Sa1_Motor_2_Statusword;

/**************************************************************************************************\
   GLOBAL: global variables (RAM) | Width: 8
\**************************************************************************************************/
extern Bool Sa1_Enable_SW_ENPO_0_1_;
extern Int8 Sa1_Motor_1_Mo__eration_display;
extern Int8 Sa1_Motor_1_Modes_of_operation;
extern Int8 Sa1_Motor_2_Mo__eration_display;
extern Int8 Sa1_Motor_2_Modes_of_operation;
extern Bool Sa1_Quit_error__0_1_;
extern Bool Sa1_Start_Homing_0_1_;
extern Bool Sa1_Testbench___rol_Enable_0_1_;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GlobalStep: Default function class for not static model step functions
\**************************************************************************************************/
extern void rtblogic(void);

#ifdef __cplusplus
}
#endif

#endif /* RTBLOGIC_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
