/**************************************************************************************************\
 *** 
 *** Simulink model       : RadarTestbench_drivesctl
 *** TargetLink subsystem : RadarTestbench_drivesctl/Testbench_Radar/Testbench_Control/rtblogic
 *** Codefile             : rtblogic.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2022-11-15 09:32:33
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 5.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 5.2 from 11-Okt-2021
 *** Code generator version  : Build Id 5.2.0.25 from 2021-10-07 14:37:36
\**************************************************************************************************/

#ifndef RTBLOGIC_H
#define RTBLOGIC_H

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "tl_basetypes.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   CONST: global constants (ROM) | Width: 8
\**************************************************************************************************/
extern const Int8 Jog;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   GlobalFcnSpecStep: Default function class for not static model step functions
\**************************************************************************************************/
extern void rtblogic(Bool Testbench_Control_Enable, Float64 angle_az, Float64 angle_el, Bool
    Enable_SW_ENPO, Float64 OperationModes, Bool Quit_error_, Bool Start_Homing, UInt16
    Motor_1_Statusword, Int32 Motor_1_Position_actual_value, Int8
    Motor_1_Modes_of_operation_display, Int32 Motor_1_VelocityActualValue, UInt16
    Motor_2_Statusword, Int32 Motor_2_Position_actual_value, Int8
    Motor_2_Modes_of_operation_display, Int32 Motor_2_VelocityActualValue, Float64
    CorrectionFactor_M1, Float64 CorrectionFactor_M2, Float64 Offset_M1, Float64 Offset_M2, UInt16 *
    Motor_1_Controlword, Int32 * Motor_1_Target_Position, UInt32 *
    Motor_1_Motor_drive_submode_select, Int8 * Motor_1_Modes_of_operation, UInt16 *
    Motor_2_Controlword, Int32 * Motor_2_Target_Position, UInt32 *
    Motor_2_Motor_drive_submode_select, Int8 * Motor_2_Modes_of_operation, Float64 *
    Motor_1_Actual_Position, Float64 * Motor_2_Actual_Position);

#ifdef __cplusplus
}
#endif

#endif /* RTBLOGIC_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
